# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/block.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'cosmoverse/proto/tendermint/types/types_pb'
require 'cosmoverse/proto/tendermint/types/evidence_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/block.proto", :syntax => :proto3) do
    add_message "tendermint.types.Block" do
      optional :header, :message, 1, "tendermint.types.Header", json_name: "header"
      optional :data, :message, 2, "tendermint.types.Data", json_name: "data"
      optional :evidence, :message, 3, "tendermint.types.EvidenceList", json_name: "evidence"
      optional :last_commit, :message, 4, "tendermint.types.Commit", json_name: "lastCommit"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        module Block
          Block = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Block").msgclass
        end
      end
    end
  end
end
