# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/evidence.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'google/protobuf/timestamp_pb'
require 'cosmoverse/proto/tendermint/types/types_pb'
require 'cosmoverse/proto/tendermint/types/validator_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/evidence.proto", :syntax => :proto3) do
    add_message "tendermint.types.Evidence" do
      oneof :sum do
        optional :duplicate_vote_evidence, :message, 1, "tendermint.types.DuplicateVoteEvidence", json_name: "duplicateVoteEvidence"
        optional :light_client_attack_evidence, :message, 2, "tendermint.types.LightClientAttackEvidence", json_name: "lightClientAttackEvidence"
      end
    end
    add_message "tendermint.types.DuplicateVoteEvidence" do
      optional :vote_a, :message, 1, "tendermint.types.Vote", json_name: "voteA"
      optional :vote_b, :message, 2, "tendermint.types.Vote", json_name: "voteB"
      optional :total_voting_power, :int64, 3, json_name: "totalVotingPower"
      optional :validator_power, :int64, 4, json_name: "validatorPower"
      optional :timestamp, :message, 5, "google.protobuf.Timestamp", json_name: "timestamp"
    end
    add_message "tendermint.types.LightClientAttackEvidence" do
      optional :conflicting_block, :message, 1, "tendermint.types.LightBlock", json_name: "conflictingBlock"
      optional :common_height, :int64, 2, json_name: "commonHeight"
      repeated :byzantine_validators, :message, 3, "tendermint.types.Validator", json_name: "byzantineValidators"
      optional :total_voting_power, :int64, 4, json_name: "totalVotingPower"
      optional :timestamp, :message, 5, "google.protobuf.Timestamp", json_name: "timestamp"
    end
    add_message "tendermint.types.EvidenceList" do
      repeated :evidence, :message, 1, "tendermint.types.Evidence", json_name: "evidence"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        module Evidence
          Evidence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Evidence").msgclass
          DuplicateVoteEvidence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.DuplicateVoteEvidence").msgclass
          LightClientAttackEvidence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.LightClientAttackEvidence").msgclass
          EvidenceList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.EvidenceList").msgclass
        end
      end
    end
  end
end
