# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/params.proto

require "google/protobuf"

require "google/protobuf/duration_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/params.proto", syntax: :proto3) do
    add_message "cosmoverse.proto.tendermint.types.ConsensusParams" do
      optional :block, :message, 1, "cosmoverse.proto.tendermint.types.BlockParams"
      optional :evidence, :message, 2, "cosmoverse.proto.tendermint.types.EvidenceParams"
      optional :validator, :message, 3, "cosmoverse.proto.tendermint.types.ValidatorParams"
      optional :version, :message, 4, "cosmoverse.proto.tendermint.types.VersionParams"
    end
    add_message "cosmoverse.proto.tendermint.types.BlockParams" do
      optional :max_bytes, :int64, 1
      optional :max_gas, :int64, 2
      optional :time_iota_ms, :int64, 3
    end
    add_message "cosmoverse.proto.tendermint.types.EvidenceParams" do
      optional :max_age_num_blocks, :int64, 1
      optional :max_age_duration, :message, 2, "google.protobuf.Duration"
      optional :max_bytes, :int64, 3
    end
    add_message "cosmoverse.proto.tendermint.types.ValidatorParams" do
      repeated :pub_key_types, :string, 1
    end
    add_message "cosmoverse.proto.tendermint.types.VersionParams" do
      optional :app_version, :uint64, 1
    end
    add_message "cosmoverse.proto.tendermint.types.HashedParams" do
      optional :block_max_bytes, :int64, 1
      optional :block_max_gas, :int64, 2
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        ConsensusParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.ConsensusParams").msgclass
        BlockParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.BlockParams").msgclass
        EvidenceParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.EvidenceParams").msgclass
        ValidatorParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.ValidatorParams").msgclass
        VersionParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.VersionParams").msgclass
        HashedParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.types.HashedParams").msgclass
      end
    end
  end
end
