# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/params.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'google/protobuf/duration_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/params.proto", :syntax => :proto3) do
    add_message "tendermint.types.ConsensusParams" do
      optional :block, :message, 1, "tendermint.types.BlockParams", json_name: "block"
      optional :evidence, :message, 2, "tendermint.types.EvidenceParams", json_name: "evidence"
      optional :validator, :message, 3, "tendermint.types.ValidatorParams", json_name: "validator"
      optional :version, :message, 4, "tendermint.types.VersionParams", json_name: "version"
    end
    add_message "tendermint.types.BlockParams" do
      optional :max_bytes, :int64, 1, json_name: "maxBytes"
      optional :max_gas, :int64, 2, json_name: "maxGas"
    end
    add_message "tendermint.types.EvidenceParams" do
      optional :max_age_num_blocks, :int64, 1, json_name: "maxAgeNumBlocks"
      optional :max_age_duration, :message, 2, "google.protobuf.Duration", json_name: "maxAgeDuration"
      optional :max_bytes, :int64, 3, json_name: "maxBytes"
    end
    add_message "tendermint.types.ValidatorParams" do
      repeated :pub_key_types, :string, 1, json_name: "pubKeyTypes"
    end
    add_message "tendermint.types.VersionParams" do
      optional :app, :uint64, 1, json_name: "app"
    end
    add_message "tendermint.types.HashedParams" do
      optional :block_max_bytes, :int64, 1, json_name: "blockMaxBytes"
      optional :block_max_gas, :int64, 2, json_name: "blockMaxGas"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        module Params
          ConsensusParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.ConsensusParams").msgclass
          BlockParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.BlockParams").msgclass
          EvidenceParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.EvidenceParams").msgclass
          ValidatorParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.ValidatorParams").msgclass
          VersionParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.VersionParams").msgclass
          HashedParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.HashedParams").msgclass
        end
      end
    end
  end
end
