# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/types.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'google/protobuf/timestamp_pb'
require 'cosmoverse/proto/tendermint/crypto/proof_pb'
require 'cosmoverse/proto/tendermint/version/types_pb'
require 'cosmoverse/proto/tendermint/types/validator_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/types.proto", :syntax => :proto3) do
    add_message "tendermint.types.PartSetHeader" do
      optional :total, :uint32, 1, json_name: "total"
      optional :hash, :bytes, 2, json_name: "hash"
    end
    add_message "tendermint.types.Part" do
      optional :index, :uint32, 1, json_name: "index"
      optional :bytes, :bytes, 2, json_name: "bytes"
      optional :proof, :message, 3, "tendermint.crypto.Proof", json_name: "proof"
    end
    add_message "tendermint.types.BlockID" do
      optional :hash, :bytes, 1, json_name: "hash"
      optional :part_set_header, :message, 2, "tendermint.types.PartSetHeader", json_name: "partSetHeader"
    end
    add_message "tendermint.types.Header" do
      optional :version, :message, 1, "tendermint.version.Consensus", json_name: "version"
      optional :chain_id, :string, 2, json_name: "chainId"
      optional :height, :int64, 3, json_name: "height"
      optional :time, :message, 4, "google.protobuf.Timestamp", json_name: "time"
      optional :last_block_id, :message, 5, "tendermint.types.BlockID", json_name: "lastBlockId"
      optional :last_commit_hash, :bytes, 6, json_name: "lastCommitHash"
      optional :data_hash, :bytes, 7, json_name: "dataHash"
      optional :validators_hash, :bytes, 8, json_name: "validatorsHash"
      optional :next_validators_hash, :bytes, 9, json_name: "nextValidatorsHash"
      optional :consensus_hash, :bytes, 10, json_name: "consensusHash"
      optional :app_hash, :bytes, 11, json_name: "appHash"
      optional :last_results_hash, :bytes, 12, json_name: "lastResultsHash"
      optional :evidence_hash, :bytes, 13, json_name: "evidenceHash"
      optional :proposer_address, :bytes, 14, json_name: "proposerAddress"
    end
    add_message "tendermint.types.Data" do
      repeated :txs, :bytes, 1, json_name: "txs"
    end
    add_message "tendermint.types.Vote" do
      optional :type, :enum, 1, "tendermint.types.SignedMsgType", json_name: "type"
      optional :height, :int64, 2, json_name: "height"
      optional :round, :int32, 3, json_name: "round"
      optional :block_id, :message, 4, "tendermint.types.BlockID", json_name: "blockId"
      optional :timestamp, :message, 5, "google.protobuf.Timestamp", json_name: "timestamp"
      optional :validator_address, :bytes, 6, json_name: "validatorAddress"
      optional :validator_index, :int32, 7, json_name: "validatorIndex"
      optional :signature, :bytes, 8, json_name: "signature"
    end
    add_message "tendermint.types.Commit" do
      optional :height, :int64, 1, json_name: "height"
      optional :round, :int32, 2, json_name: "round"
      optional :block_id, :message, 3, "tendermint.types.BlockID", json_name: "blockId"
      repeated :signatures, :message, 4, "tendermint.types.CommitSig", json_name: "signatures"
    end
    add_message "tendermint.types.CommitSig" do
      optional :block_id_flag, :enum, 1, "tendermint.types.BlockIDFlag", json_name: "blockIdFlag"
      optional :validator_address, :bytes, 2, json_name: "validatorAddress"
      optional :timestamp, :message, 3, "google.protobuf.Timestamp", json_name: "timestamp"
      optional :signature, :bytes, 4, json_name: "signature"
    end
    add_message "tendermint.types.Proposal" do
      optional :type, :enum, 1, "tendermint.types.SignedMsgType", json_name: "type"
      optional :height, :int64, 2, json_name: "height"
      optional :round, :int32, 3, json_name: "round"
      optional :pol_round, :int32, 4, json_name: "polRound"
      optional :block_id, :message, 5, "tendermint.types.BlockID", json_name: "blockId"
      optional :timestamp, :message, 6, "google.protobuf.Timestamp", json_name: "timestamp"
      optional :signature, :bytes, 7, json_name: "signature"
    end
    add_message "tendermint.types.SignedHeader" do
      optional :header, :message, 1, "tendermint.types.Header", json_name: "header"
      optional :commit, :message, 2, "tendermint.types.Commit", json_name: "commit"
    end
    add_message "tendermint.types.LightBlock" do
      optional :signed_header, :message, 1, "tendermint.types.SignedHeader", json_name: "signedHeader"
      optional :validator_set, :message, 2, "tendermint.types.ValidatorSet", json_name: "validatorSet"
    end
    add_message "tendermint.types.BlockMeta" do
      optional :block_id, :message, 1, "tendermint.types.BlockID", json_name: "blockId"
      optional :block_size, :int64, 2, json_name: "blockSize"
      optional :header, :message, 3, "tendermint.types.Header", json_name: "header"
      optional :num_txs, :int64, 4, json_name: "numTxs"
    end
    add_message "tendermint.types.TxProof" do
      optional :root_hash, :bytes, 1, json_name: "rootHash"
      optional :data, :bytes, 2, json_name: "data"
      optional :proof, :message, 3, "tendermint.crypto.Proof", json_name: "proof"
    end
    add_enum "tendermint.types.BlockIDFlag" do
      value :BLOCK_ID_FLAG_UNKNOWN, 0
      value :BLOCK_ID_FLAG_ABSENT, 1
      value :BLOCK_ID_FLAG_COMMIT, 2
      value :BLOCK_ID_FLAG_NIL, 3
    end
    add_enum "tendermint.types.SignedMsgType" do
      value :SIGNED_MSG_TYPE_UNKNOWN, 0
      value :SIGNED_MSG_TYPE_PREVOTE, 1
      value :SIGNED_MSG_TYPE_PRECOMMIT, 2
      value :SIGNED_MSG_TYPE_PROPOSAL, 32
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        module Types
          PartSetHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.PartSetHeader").msgclass
          Part = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Part").msgclass
          BlockID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.BlockID").msgclass
          Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Header").msgclass
          Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Data").msgclass
          Vote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Vote").msgclass
          Commit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Commit").msgclass
          CommitSig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.CommitSig").msgclass
          Proposal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Proposal").msgclass
          SignedHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.SignedHeader").msgclass
          LightBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.LightBlock").msgclass
          BlockMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.BlockMeta").msgclass
          TxProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.TxProof").msgclass
          BlockIDFlag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.BlockIDFlag").enummodule
          SignedMsgType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.SignedMsgType").enummodule
        end
      end
    end
  end
end
