# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/validator.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'cosmoverse/proto/tendermint/crypto/keys_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/types/validator.proto", :syntax => :proto3) do
    add_message "tendermint.types.ValidatorSet" do
      repeated :validators, :message, 1, "tendermint.types.Validator", json_name: "validators"
      optional :proposer, :message, 2, "tendermint.types.Validator", json_name: "proposer"
      optional :total_voting_power, :int64, 3, json_name: "totalVotingPower"
    end
    add_message "tendermint.types.Validator" do
      optional :address, :bytes, 1, json_name: "address"
      optional :pub_key, :message, 2, "tendermint.crypto.PublicKey", json_name: "pubKey"
      optional :voting_power, :int64, 3, json_name: "votingPower"
      optional :proposer_priority, :int64, 4, json_name: "proposerPriority"
    end
    add_message "tendermint.types.SimpleValidator" do
      optional :pub_key, :message, 1, "tendermint.crypto.PublicKey", json_name: "pubKey"
      optional :voting_power, :int64, 2, json_name: "votingPower"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Types
        module Validator
          ValidatorSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.ValidatorSet").msgclass
          Validator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.Validator").msgclass
          SimpleValidator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.types.SimpleValidator").msgclass
        end
      end
    end
  end
end
