require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/HashSyntax:
  Exclude:
    - lib/cosmoverse/proto/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - lib/cosmoverse/proto/**/*

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/cosmoverse/proto/**/*

Metrics/BlockLength:
  Exclude:
    - lib/cosmoverse/proto/**/*
    - lib/cosmoverse/cosmos/gogoproto/**/*

Lint/EmptyBlock:
  Exclude:
    - lib/cosmoverse/proto/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - lib/cosmoverse/proto/**/*
