# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/query/v1beta1/pagination.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/base/query/v1beta1/pagination.proto", syntax: :proto3) do
    add_message "cosmoverse.proto.cosmos.base.query.v1beta1.PageRequest" do
      optional :key, :bytes, 1
      optional :offset, :uint64, 2
      optional :limit, :uint64, 3
      optional :count_total, :bool, 4
      optional :reverse, :bool, 5
    end
    add_message "cosmoverse.proto.cosmos.base.query.v1beta1.PageResponse" do
      optional :next_key, :bytes, 1
      optional :total, :uint64, 2
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Base
        module Query
          module V1beta1
            PageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.base.query.v1beta1.PageRequest").msgclass
            PageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.base.query.v1beta1.PageResponse").msgclass
          end
        end
      end
    end
  end
end
