# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amino/amino.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("amino/amino.proto", :syntax => :proto3) do
  end
end

module Cosmoverse
  module Proto
    module Amino
    end
  end
end
