# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/version/types.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/version/types.proto", :syntax => :proto3) do
    add_message "tendermint.version.App" do
      optional :protocol, :uint64, 1, json_name: "protocol"
      optional :software, :string, 2, json_name: "software"
    end
    add_message "tendermint.version.Consensus" do
      optional :block, :uint64, 1, json_name: "block"
      optional :app, :uint64, 2, json_name: "app"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Version
        module Types
          App = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.version.App").msgclass
          Consensus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.version.Consensus").msgclass
        end
      end
    end
  end
end
