# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/version/types.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/version/types.proto", syntax: :proto3) do
    add_message "cosmoverse.proto.tendermint.version.App" do
      optional :protocol, :uint64, 1
      optional :software, :string, 2
    end
    add_message "cosmoverse.proto.tendermint.version.Consensus" do
      optional :block, :uint64, 1
      optional :app, :uint64, 2
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Version
        App = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.version.App").msgclass
        Consensus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.version.Consensus").msgclass
      end
    end
  end
end
