# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/transfer/v1/query.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'cosmoverse/proto/cosmos/base/query/v1beta1/pagination_pb'
require 'cosmoverse/proto/ibc/applications/transfer/v1/transfer_pb'
require 'google/api/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ibc/applications/transfer/v1/query.proto", :syntax => :proto3) do
    add_message "ibc.applications.transfer.v1.QueryDenomTraceRequest" do
      optional :hash, :string, 1, json_name: "hash"
    end
    add_message "ibc.applications.transfer.v1.QueryDenomTraceResponse" do
      optional :denom_trace, :message, 1, "ibc.applications.transfer.v1.DenomTrace", json_name: "denomTrace"
    end
    add_message "ibc.applications.transfer.v1.QueryDenomTracesRequest" do
      optional :pagination, :message, 1, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "ibc.applications.transfer.v1.QueryDenomTracesResponse" do
      repeated :denom_traces, :message, 1, "ibc.applications.transfer.v1.DenomTrace", json_name: "denomTraces"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "ibc.applications.transfer.v1.QueryParamsRequest" do
    end
    add_message "ibc.applications.transfer.v1.QueryParamsResponse" do
      optional :params, :message, 1, "ibc.applications.transfer.v1.Params", json_name: "params"
    end
    add_message "ibc.applications.transfer.v1.QueryDenomHashRequest" do
      optional :trace, :string, 1, json_name: "trace"
    end
    add_message "ibc.applications.transfer.v1.QueryDenomHashResponse" do
      optional :hash, :string, 1, json_name: "hash"
    end
    add_message "ibc.applications.transfer.v1.QueryEscrowAddressRequest" do
      optional :port_id, :string, 1, json_name: "portId"
      optional :channel_id, :string, 2, json_name: "channelId"
    end
    add_message "ibc.applications.transfer.v1.QueryEscrowAddressResponse" do
      optional :escrow_address, :string, 1, json_name: "escrowAddress"
    end
  end
end

module Cosmoverse
  module Proto
    module Ibc
      module Applications
        module Transfer
          module V1
            QueryDenomTraceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomTraceRequest").msgclass
            QueryDenomTraceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomTraceResponse").msgclass
            QueryDenomTracesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomTracesRequest").msgclass
            QueryDenomTracesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomTracesResponse").msgclass
            QueryParamsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryParamsRequest").msgclass
            QueryParamsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryParamsResponse").msgclass
            QueryDenomHashRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomHashRequest").msgclass
            QueryDenomHashResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryDenomHashResponse").msgclass
            QueryEscrowAddressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryEscrowAddressRequest").msgclass
            QueryEscrowAddressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.QueryEscrowAddressResponse").msgclass
          end
        end
      end
    end
  end
end
