# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ibc/applications/transfer/v1/query.proto for package 'Cosmoverse.Proto.Ibc.Applications.Transfer.V1'

require 'grpc'
require 'cosmoverse/proto/ibc/applications/transfer/v1/query_pb'

module Cosmoverse
  module Proto
    module Ibc
      module Applications
        module Transfer
          module V1
            module Query
              # Query provides defines the gRPC querier service.
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'ibc.applications.transfer.v1.Query'

                # DenomTrace queries a denomination trace information.
                rpc :DenomTrace, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomTraceRequest, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomTraceResponse
                # DenomTraces queries all denomination traces.
                rpc :DenomTraces, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomTracesRequest, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomTracesResponse
                # Params queries all parameters of the ibc-transfer module.
                rpc :Params, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryParamsRequest, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryParamsResponse
                # DenomHash queries a denomination hash information.
                rpc :DenomHash, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomHashRequest, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryDenomHashResponse
                # EscrowAddress returns the escrow address for a particular port and channel id.
                rpc :EscrowAddress, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryEscrowAddressRequest, ::Cosmoverse::Proto::Ibc::Applications::Transfer::V1::QueryEscrowAddressResponse
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
