# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/transfer/v1/transfer.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ibc/applications/transfer/v1/transfer.proto", :syntax => :proto3) do
    add_message "ibc.applications.transfer.v1.DenomTrace" do
      optional :path, :string, 1, json_name: "path"
      optional :base_denom, :string, 2, json_name: "baseDenom"
    end
    add_message "ibc.applications.transfer.v1.Params" do
      optional :send_enabled, :bool, 1, json_name: "sendEnabled"
      optional :receive_enabled, :bool, 2, json_name: "receiveEnabled"
    end
  end
end

module Cosmoverse
  module Proto
    module Ibc
      module Applications
        module Transfer
          module V1
            DenomTrace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.DenomTrace").msgclass
            Params = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ibc.applications.transfer.v1.Params").msgclass
          end
        end
      end
    end
  end
end
