# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/tx/signing/v1beta1/signing.proto

require 'google/protobuf'

require 'cosmoverse/proto/cosmos/crypto/multisig/v1beta1/multisig_pb'
require 'google/protobuf/any_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/tx/signing/v1beta1/signing.proto", :syntax => :proto3) do
    add_message "cosmos.tx.signing.v1beta1.SignatureDescriptors" do
      repeated :signatures, :message, 1, "cosmos.tx.signing.v1beta1.SignatureDescriptor", json_name: "signatures"
    end
    add_message "cosmos.tx.signing.v1beta1.SignatureDescriptor" do
      optional :public_key, :message, 1, "google.protobuf.Any", json_name: "publicKey"
      optional :data, :message, 2, "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data", json_name: "data"
      optional :sequence, :uint64, 3, json_name: "sequence"
    end
    add_message "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data" do
      oneof :sum do
        optional :single, :message, 1, "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Single", json_name: "single"
        optional :multi, :message, 2, "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Multi", json_name: "multi"
      end
    end
    add_message "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Single" do
      optional :mode, :enum, 1, "cosmos.tx.signing.v1beta1.SignMode", json_name: "mode"
      optional :signature, :bytes, 2, json_name: "signature"
    end
    add_message "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Multi" do
      optional :bitarray, :message, 1, "cosmos.crypto.multisig.v1beta1.CompactBitArray", json_name: "bitarray"
      repeated :signatures, :message, 2, "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data", json_name: "signatures"
    end
    add_enum "cosmos.tx.signing.v1beta1.SignMode" do
      value :SIGN_MODE_UNSPECIFIED, 0
      value :SIGN_MODE_DIRECT, 1
      value :SIGN_MODE_TEXTUAL, 2
      value :SIGN_MODE_DIRECT_AUX, 3
      value :SIGN_MODE_LEGACY_AMINO_JSON, 127
      value :SIGN_MODE_EIP_191, 191
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Tx
        module Signing
          module V1beta1
            module Signing
              SignatureDescriptors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignatureDescriptors").msgclass
              SignatureDescriptor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignatureDescriptor").msgclass
              SignatureDescriptor::Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignatureDescriptor.Data").msgclass
              SignatureDescriptor::Data::Single = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Single").msgclass
              SignatureDescriptor::Data::Multi = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Multi").msgclass
              SignMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.signing.v1beta1.SignMode").enummodule
            end
          end
        end
      end
    end
  end
end
