# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/abci/types.proto

require 'google/protobuf'

require 'cosmoverse/proto/tendermint/crypto/proof_pb'
require 'cosmoverse/proto/tendermint/types/types_pb'
require 'cosmoverse/proto/tendermint/crypto/keys_pb'
require 'cosmoverse/proto/tendermint/types/params_pb'
require 'google/protobuf/timestamp_pb'
require 'cosmoverse/proto/gogoproto/gogo_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/abci/types.proto", :syntax => :proto3) do
    add_message "tendermint.abci.Request" do
      oneof :value do
        optional :echo, :message, 1, "tendermint.abci.RequestEcho", json_name: "echo"
        optional :flush, :message, 2, "tendermint.abci.RequestFlush", json_name: "flush"
        optional :info, :message, 3, "tendermint.abci.RequestInfo", json_name: "info"
        optional :init_chain, :message, 5, "tendermint.abci.RequestInitChain", json_name: "initChain"
        optional :query, :message, 6, "tendermint.abci.RequestQuery", json_name: "query"
        optional :begin_block, :message, 7, "tendermint.abci.RequestBeginBlock", json_name: "beginBlock"
        optional :check_tx, :message, 8, "tendermint.abci.RequestCheckTx", json_name: "checkTx"
        optional :deliver_tx, :message, 9, "tendermint.abci.RequestDeliverTx", json_name: "deliverTx"
        optional :end_block, :message, 10, "tendermint.abci.RequestEndBlock", json_name: "endBlock"
        optional :commit, :message, 11, "tendermint.abci.RequestCommit", json_name: "commit"
        optional :list_snapshots, :message, 12, "tendermint.abci.RequestListSnapshots", json_name: "listSnapshots"
        optional :offer_snapshot, :message, 13, "tendermint.abci.RequestOfferSnapshot", json_name: "offerSnapshot"
        optional :load_snapshot_chunk, :message, 14, "tendermint.abci.RequestLoadSnapshotChunk", json_name: "loadSnapshotChunk"
        optional :apply_snapshot_chunk, :message, 15, "tendermint.abci.RequestApplySnapshotChunk", json_name: "applySnapshotChunk"
        optional :prepare_proposal, :message, 16, "tendermint.abci.RequestPrepareProposal", json_name: "prepareProposal"
        optional :process_proposal, :message, 17, "tendermint.abci.RequestProcessProposal", json_name: "processProposal"
      end
    end
    add_message "tendermint.abci.RequestEcho" do
      optional :message, :string, 1, json_name: "message"
    end
    add_message "tendermint.abci.RequestFlush" do
    end
    add_message "tendermint.abci.RequestInfo" do
      optional :version, :string, 1, json_name: "version"
      optional :block_version, :uint64, 2, json_name: "blockVersion"
      optional :p2p_version, :uint64, 3, json_name: "p2pVersion"
      optional :abci_version, :string, 4, json_name: "abciVersion"
    end
    add_message "tendermint.abci.RequestInitChain" do
      optional :time, :message, 1, "google.protobuf.Timestamp", json_name: "time"
      optional :chain_id, :string, 2, json_name: "chainId"
      optional :consensus_params, :message, 3, "tendermint.types.ConsensusParams", json_name: "consensusParams"
      repeated :validators, :message, 4, "tendermint.abci.ValidatorUpdate", json_name: "validators"
      optional :app_state_bytes, :bytes, 5, json_name: "appStateBytes"
      optional :initial_height, :int64, 6, json_name: "initialHeight"
    end
    add_message "tendermint.abci.RequestQuery" do
      optional :data, :bytes, 1, json_name: "data"
      optional :path, :string, 2, json_name: "path"
      optional :height, :int64, 3, json_name: "height"
      optional :prove, :bool, 4, json_name: "prove"
    end
    add_message "tendermint.abci.RequestBeginBlock" do
      optional :hash, :bytes, 1, json_name: "hash"
      optional :header, :message, 2, "tendermint.types.Header", json_name: "header"
      optional :last_commit_info, :message, 3, "tendermint.abci.CommitInfo", json_name: "lastCommitInfo"
      repeated :byzantine_validators, :message, 4, "tendermint.abci.Misbehavior", json_name: "byzantineValidators"
    end
    add_message "tendermint.abci.RequestCheckTx" do
      optional :tx, :bytes, 1, json_name: "tx"
      optional :type, :enum, 2, "tendermint.abci.CheckTxType", json_name: "type"
    end
    add_message "tendermint.abci.RequestDeliverTx" do
      optional :tx, :bytes, 1, json_name: "tx"
    end
    add_message "tendermint.abci.RequestEndBlock" do
      optional :height, :int64, 1, json_name: "height"
    end
    add_message "tendermint.abci.RequestCommit" do
    end
    add_message "tendermint.abci.RequestListSnapshots" do
    end
    add_message "tendermint.abci.RequestOfferSnapshot" do
      optional :snapshot, :message, 1, "tendermint.abci.Snapshot", json_name: "snapshot"
      optional :app_hash, :bytes, 2, json_name: "appHash"
    end
    add_message "tendermint.abci.RequestLoadSnapshotChunk" do
      optional :height, :uint64, 1, json_name: "height"
      optional :format, :uint32, 2, json_name: "format"
      optional :chunk, :uint32, 3, json_name: "chunk"
    end
    add_message "tendermint.abci.RequestApplySnapshotChunk" do
      optional :index, :uint32, 1, json_name: "index"
      optional :chunk, :bytes, 2, json_name: "chunk"
      optional :sender, :string, 3, json_name: "sender"
    end
    add_message "tendermint.abci.RequestPrepareProposal" do
      optional :max_tx_bytes, :int64, 1, json_name: "maxTxBytes"
      repeated :txs, :bytes, 2, json_name: "txs"
      optional :local_last_commit, :message, 3, "tendermint.abci.ExtendedCommitInfo", json_name: "localLastCommit"
      repeated :misbehavior, :message, 4, "tendermint.abci.Misbehavior", json_name: "misbehavior"
      optional :height, :int64, 5, json_name: "height"
      optional :time, :message, 6, "google.protobuf.Timestamp", json_name: "time"
      optional :next_validators_hash, :bytes, 7, json_name: "nextValidatorsHash"
      optional :proposer_address, :bytes, 8, json_name: "proposerAddress"
    end
    add_message "tendermint.abci.RequestProcessProposal" do
      repeated :txs, :bytes, 1, json_name: "txs"
      optional :proposed_last_commit, :message, 2, "tendermint.abci.CommitInfo", json_name: "proposedLastCommit"
      repeated :misbehavior, :message, 3, "tendermint.abci.Misbehavior", json_name: "misbehavior"
      optional :hash, :bytes, 4, json_name: "hash"
      optional :height, :int64, 5, json_name: "height"
      optional :time, :message, 6, "google.protobuf.Timestamp", json_name: "time"
      optional :next_validators_hash, :bytes, 7, json_name: "nextValidatorsHash"
      optional :proposer_address, :bytes, 8, json_name: "proposerAddress"
    end
    add_message "tendermint.abci.Response" do
      oneof :value do
        optional :exception, :message, 1, "tendermint.abci.ResponseException", json_name: "exception"
        optional :echo, :message, 2, "tendermint.abci.ResponseEcho", json_name: "echo"
        optional :flush, :message, 3, "tendermint.abci.ResponseFlush", json_name: "flush"
        optional :info, :message, 4, "tendermint.abci.ResponseInfo", json_name: "info"
        optional :init_chain, :message, 6, "tendermint.abci.ResponseInitChain", json_name: "initChain"
        optional :query, :message, 7, "tendermint.abci.ResponseQuery", json_name: "query"
        optional :begin_block, :message, 8, "tendermint.abci.ResponseBeginBlock", json_name: "beginBlock"
        optional :check_tx, :message, 9, "tendermint.abci.ResponseCheckTx", json_name: "checkTx"
        optional :deliver_tx, :message, 10, "tendermint.abci.ResponseDeliverTx", json_name: "deliverTx"
        optional :end_block, :message, 11, "tendermint.abci.ResponseEndBlock", json_name: "endBlock"
        optional :commit, :message, 12, "tendermint.abci.ResponseCommit", json_name: "commit"
        optional :list_snapshots, :message, 13, "tendermint.abci.ResponseListSnapshots", json_name: "listSnapshots"
        optional :offer_snapshot, :message, 14, "tendermint.abci.ResponseOfferSnapshot", json_name: "offerSnapshot"
        optional :load_snapshot_chunk, :message, 15, "tendermint.abci.ResponseLoadSnapshotChunk", json_name: "loadSnapshotChunk"
        optional :apply_snapshot_chunk, :message, 16, "tendermint.abci.ResponseApplySnapshotChunk", json_name: "applySnapshotChunk"
        optional :prepare_proposal, :message, 17, "tendermint.abci.ResponsePrepareProposal", json_name: "prepareProposal"
        optional :process_proposal, :message, 18, "tendermint.abci.ResponseProcessProposal", json_name: "processProposal"
      end
    end
    add_message "tendermint.abci.ResponseException" do
      optional :error, :string, 1, json_name: "error"
    end
    add_message "tendermint.abci.ResponseEcho" do
      optional :message, :string, 1, json_name: "message"
    end
    add_message "tendermint.abci.ResponseFlush" do
    end
    add_message "tendermint.abci.ResponseInfo" do
      optional :data, :string, 1, json_name: "data"
      optional :version, :string, 2, json_name: "version"
      optional :app_version, :uint64, 3, json_name: "appVersion"
      optional :last_block_height, :int64, 4, json_name: "lastBlockHeight"
      optional :last_block_app_hash, :bytes, 5, json_name: "lastBlockAppHash"
    end
    add_message "tendermint.abci.ResponseInitChain" do
      optional :consensus_params, :message, 1, "tendermint.types.ConsensusParams", json_name: "consensusParams"
      repeated :validators, :message, 2, "tendermint.abci.ValidatorUpdate", json_name: "validators"
      optional :app_hash, :bytes, 3, json_name: "appHash"
    end
    add_message "tendermint.abci.ResponseQuery" do
      optional :code, :uint32, 1, json_name: "code"
      optional :log, :string, 3, json_name: "log"
      optional :info, :string, 4, json_name: "info"
      optional :index, :int64, 5, json_name: "index"
      optional :key, :bytes, 6, json_name: "key"
      optional :value, :bytes, 7, json_name: "value"
      optional :proof_ops, :message, 8, "tendermint.crypto.ProofOps", json_name: "proofOps"
      optional :height, :int64, 9, json_name: "height"
      optional :codespace, :string, 10, json_name: "codespace"
    end
    add_message "tendermint.abci.ResponseBeginBlock" do
      repeated :events, :message, 1, "tendermint.abci.Event", json_name: "events"
    end
    add_message "tendermint.abci.ResponseCheckTx" do
      optional :code, :uint32, 1, json_name: "code"
      optional :data, :bytes, 2, json_name: "data"
      optional :log, :string, 3, json_name: "log"
      optional :info, :string, 4, json_name: "info"
      optional :gas_wanted, :int64, 5, json_name: "gas_wanted"
      optional :gas_used, :int64, 6, json_name: "gas_used"
      repeated :events, :message, 7, "tendermint.abci.Event", json_name: "events"
      optional :codespace, :string, 8, json_name: "codespace"
      optional :sender, :string, 9, json_name: "sender"
      optional :priority, :int64, 10, json_name: "priority"
      optional :mempool_error, :string, 11, json_name: "mempoolError"
    end
    add_message "tendermint.abci.ResponseDeliverTx" do
      optional :code, :uint32, 1, json_name: "code"
      optional :data, :bytes, 2, json_name: "data"
      optional :log, :string, 3, json_name: "log"
      optional :info, :string, 4, json_name: "info"
      optional :gas_wanted, :int64, 5, json_name: "gas_wanted"
      optional :gas_used, :int64, 6, json_name: "gas_used"
      repeated :events, :message, 7, "tendermint.abci.Event", json_name: "events"
      optional :codespace, :string, 8, json_name: "codespace"
    end
    add_message "tendermint.abci.ResponseEndBlock" do
      repeated :validator_updates, :message, 1, "tendermint.abci.ValidatorUpdate", json_name: "validatorUpdates"
      optional :consensus_param_updates, :message, 2, "tendermint.types.ConsensusParams", json_name: "consensusParamUpdates"
      repeated :events, :message, 3, "tendermint.abci.Event", json_name: "events"
    end
    add_message "tendermint.abci.ResponseCommit" do
      optional :data, :bytes, 2, json_name: "data"
      optional :retain_height, :int64, 3, json_name: "retainHeight"
    end
    add_message "tendermint.abci.ResponseListSnapshots" do
      repeated :snapshots, :message, 1, "tendermint.abci.Snapshot", json_name: "snapshots"
    end
    add_message "tendermint.abci.ResponseOfferSnapshot" do
      optional :result, :enum, 1, "tendermint.abci.ResponseOfferSnapshot.Result", json_name: "result"
    end
    add_enum "tendermint.abci.ResponseOfferSnapshot.Result" do
      value :UNKNOWN, 0
      value :ACCEPT, 1
      value :ABORT, 2
      value :REJECT, 3
      value :REJECT_FORMAT, 4
      value :REJECT_SENDER, 5
    end
    add_message "tendermint.abci.ResponseLoadSnapshotChunk" do
      optional :chunk, :bytes, 1, json_name: "chunk"
    end
    add_message "tendermint.abci.ResponseApplySnapshotChunk" do
      optional :result, :enum, 1, "tendermint.abci.ResponseApplySnapshotChunk.Result", json_name: "result"
      repeated :refetch_chunks, :uint32, 2, json_name: "refetchChunks"
      repeated :reject_senders, :string, 3, json_name: "rejectSenders"
    end
    add_enum "tendermint.abci.ResponseApplySnapshotChunk.Result" do
      value :UNKNOWN, 0
      value :ACCEPT, 1
      value :ABORT, 2
      value :RETRY, 3
      value :RETRY_SNAPSHOT, 4
      value :REJECT_SNAPSHOT, 5
    end
    add_message "tendermint.abci.ResponsePrepareProposal" do
      repeated :txs, :bytes, 1, json_name: "txs"
    end
    add_message "tendermint.abci.ResponseProcessProposal" do
      optional :status, :enum, 1, "tendermint.abci.ResponseProcessProposal.ProposalStatus", json_name: "status"
    end
    add_enum "tendermint.abci.ResponseProcessProposal.ProposalStatus" do
      value :UNKNOWN, 0
      value :ACCEPT, 1
      value :REJECT, 2
    end
    add_message "tendermint.abci.CommitInfo" do
      optional :round, :int32, 1, json_name: "round"
      repeated :votes, :message, 2, "tendermint.abci.VoteInfo", json_name: "votes"
    end
    add_message "tendermint.abci.ExtendedCommitInfo" do
      optional :round, :int32, 1, json_name: "round"
      repeated :votes, :message, 2, "tendermint.abci.ExtendedVoteInfo", json_name: "votes"
    end
    add_message "tendermint.abci.Event" do
      optional :type, :string, 1, json_name: "type"
      repeated :attributes, :message, 2, "tendermint.abci.EventAttribute", json_name: "attributes"
    end
    add_message "tendermint.abci.EventAttribute" do
      optional :key, :string, 1, json_name: "key"
      optional :value, :string, 2, json_name: "value"
      optional :index, :bool, 3, json_name: "index"
    end
    add_message "tendermint.abci.TxResult" do
      optional :height, :int64, 1, json_name: "height"
      optional :index, :uint32, 2, json_name: "index"
      optional :tx, :bytes, 3, json_name: "tx"
      optional :result, :message, 4, "tendermint.abci.ResponseDeliverTx", json_name: "result"
    end
    add_message "tendermint.abci.Validator" do
      optional :address, :bytes, 1, json_name: "address"
      optional :power, :int64, 3, json_name: "power"
    end
    add_message "tendermint.abci.ValidatorUpdate" do
      optional :pub_key, :message, 1, "tendermint.crypto.PublicKey", json_name: "pubKey"
      optional :power, :int64, 2, json_name: "power"
    end
    add_message "tendermint.abci.VoteInfo" do
      optional :validator, :message, 1, "tendermint.abci.Validator", json_name: "validator"
      optional :signed_last_block, :bool, 2, json_name: "signedLastBlock"
    end
    add_message "tendermint.abci.ExtendedVoteInfo" do
      optional :validator, :message, 1, "tendermint.abci.Validator", json_name: "validator"
      optional :signed_last_block, :bool, 2, json_name: "signedLastBlock"
      optional :vote_extension, :bytes, 3, json_name: "voteExtension"
    end
    add_message "tendermint.abci.Misbehavior" do
      optional :type, :enum, 1, "tendermint.abci.MisbehaviorType", json_name: "type"
      optional :validator, :message, 2, "tendermint.abci.Validator", json_name: "validator"
      optional :height, :int64, 3, json_name: "height"
      optional :time, :message, 4, "google.protobuf.Timestamp", json_name: "time"
      optional :total_voting_power, :int64, 5, json_name: "totalVotingPower"
    end
    add_message "tendermint.abci.Snapshot" do
      optional :height, :uint64, 1, json_name: "height"
      optional :format, :uint32, 2, json_name: "format"
      optional :chunks, :uint32, 3, json_name: "chunks"
      optional :hash, :bytes, 4, json_name: "hash"
      optional :metadata, :bytes, 5, json_name: "metadata"
    end
    add_enum "tendermint.abci.CheckTxType" do
      value :NEW, 0
      value :RECHECK, 1
    end
    add_enum "tendermint.abci.MisbehaviorType" do
      value :UNKNOWN, 0
      value :DUPLICATE_VOTE, 1
      value :LIGHT_CLIENT_ATTACK, 2
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Abci
        module Types
          Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Request").msgclass
          RequestEcho = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestEcho").msgclass
          RequestFlush = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestFlush").msgclass
          RequestInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestInfo").msgclass
          RequestInitChain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestInitChain").msgclass
          RequestQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestQuery").msgclass
          RequestBeginBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestBeginBlock").msgclass
          RequestCheckTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestCheckTx").msgclass
          RequestDeliverTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestDeliverTx").msgclass
          RequestEndBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestEndBlock").msgclass
          RequestCommit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestCommit").msgclass
          RequestListSnapshots = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestListSnapshots").msgclass
          RequestOfferSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestOfferSnapshot").msgclass
          RequestLoadSnapshotChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestLoadSnapshotChunk").msgclass
          RequestApplySnapshotChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestApplySnapshotChunk").msgclass
          RequestPrepareProposal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestPrepareProposal").msgclass
          RequestProcessProposal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.RequestProcessProposal").msgclass
          Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Response").msgclass
          ResponseException = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseException").msgclass
          ResponseEcho = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseEcho").msgclass
          ResponseFlush = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseFlush").msgclass
          ResponseInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseInfo").msgclass
          ResponseInitChain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseInitChain").msgclass
          ResponseQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseQuery").msgclass
          ResponseBeginBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseBeginBlock").msgclass
          ResponseCheckTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseCheckTx").msgclass
          ResponseDeliverTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseDeliverTx").msgclass
          ResponseEndBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseEndBlock").msgclass
          ResponseCommit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseCommit").msgclass
          ResponseListSnapshots = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseListSnapshots").msgclass
          ResponseOfferSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseOfferSnapshot").msgclass
          ResponseOfferSnapshot::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseOfferSnapshot.Result").enummodule
          ResponseLoadSnapshotChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseLoadSnapshotChunk").msgclass
          ResponseApplySnapshotChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseApplySnapshotChunk").msgclass
          ResponseApplySnapshotChunk::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseApplySnapshotChunk.Result").enummodule
          ResponsePrepareProposal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponsePrepareProposal").msgclass
          ResponseProcessProposal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseProcessProposal").msgclass
          ResponseProcessProposal::ProposalStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ResponseProcessProposal.ProposalStatus").enummodule
          CommitInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.CommitInfo").msgclass
          ExtendedCommitInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ExtendedCommitInfo").msgclass
          Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Event").msgclass
          EventAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.EventAttribute").msgclass
          TxResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.TxResult").msgclass
          Validator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Validator").msgclass
          ValidatorUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ValidatorUpdate").msgclass
          VoteInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.VoteInfo").msgclass
          ExtendedVoteInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.ExtendedVoteInfo").msgclass
          Misbehavior = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Misbehavior").msgclass
          Snapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.Snapshot").msgclass
          CheckTxType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.CheckTxType").enummodule
          MisbehaviorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tendermint.abci.MisbehaviorType").enummodule
        end
      end
    end
  end
end
