# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/crypto/proof.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tendermint/crypto/proof.proto", syntax: :proto3) do
    add_message "cosmoverse.proto.tendermint.crypto.Proof" do
      optional :total, :int64, 1
      optional :index, :int64, 2
      optional :leaf_hash, :bytes, 3
      repeated :aunts, :bytes, 4
    end
    add_message "cosmoverse.proto.tendermint.crypto.ValueOp" do
      optional :key, :bytes, 1
      optional :proof, :message, 2, "cosmoverse.proto.tendermint.crypto.Proof"
    end
    add_message "cosmoverse.proto.tendermint.crypto.DominoOp" do
      optional :key, :string, 1
      optional :input, :string, 2
      optional :output, :string, 3
    end
    add_message "cosmoverse.proto.tendermint.crypto.ProofOp" do
      optional :type, :string, 1
      optional :key, :bytes, 2
      optional :data, :bytes, 3
    end
    add_message "cosmoverse.proto.tendermint.crypto.ProofOps" do
      repeated :ops, :message, 1, "cosmoverse.proto.tendermint.crypto.ProofOp"
    end
  end
end

module Cosmoverse
  module Proto
    module Tendermint
      module Crypto
        Proof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.crypto.Proof").msgclass
        ValueOp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.crypto.ValueOp").msgclass
        DominoOp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.crypto.DominoOp").msgclass
        ProofOp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.crypto.ProofOp").msgclass
        ProofOps = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.tendermint.crypto.ProofOps").msgclass
      end
    end
  end
end
