# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/crypto/multisig/v1beta1/multisig.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/crypto/multisig/v1beta1/multisig.proto", :syntax => :proto3) do
    add_message "cosmos.crypto.multisig.v1beta1.MultiSignature" do
      repeated :signatures, :bytes, 1, json_name: "signatures"
    end
    add_message "cosmos.crypto.multisig.v1beta1.CompactBitArray" do
      optional :extra_bits_stored, :uint32, 1, json_name: "extraBitsStored"
      optional :elems, :bytes, 2, json_name: "elems"
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Crypto
        module Multisig
          module V1beta1
            module Multisig
              MultiSignature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.crypto.multisig.v1beta1.MultiSignature").msgclass
              CompactBitArray = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.crypto.multisig.v1beta1.CompactBitArray").msgclass
            end
          end
        end
      end
    end
  end
end
