# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/query/v1/query.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/query/v1/query.proto", :syntax => :proto3) do
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Query
        module V1
          module Query
          end
        end
      end
    end
  end
end
