# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/msg/v1/msg.proto

require "google/protobuf"

require "google/protobuf/descriptor_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/msg/v1/msg.proto", syntax: :proto3) do
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Msg
        module V1
        end
      end
    end
  end
end
