# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/bank/v1beta1/bank.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'cosmoverse/proto/cosmos_proto/cosmos_pb'
require 'cosmoverse/proto/cosmos/base/v1beta1/coin_pb'
require 'cosmoverse/proto/cosmos/msg/v1/msg_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/bank/v1beta1/bank.proto", :syntax => :proto3) do
    add_message "cosmos.bank.v1beta1.Params" do
      repeated :send_enabled, :message, 1, "cosmos.bank.v1beta1.SendEnabled", json_name: "sendEnabled"
      optional :default_send_enabled, :bool, 2, json_name: "defaultSendEnabled"
    end
    add_message "cosmos.bank.v1beta1.SendEnabled" do
      optional :denom, :string, 1, json_name: "denom"
      optional :enabled, :bool, 2, json_name: "enabled"
    end
    add_message "cosmos.bank.v1beta1.Input" do
      optional :address, :string, 1, json_name: "address"
      repeated :coins, :message, 2, "cosmos.base.v1beta1.Coin", json_name: "coins"
    end
    add_message "cosmos.bank.v1beta1.Output" do
      optional :address, :string, 1, json_name: "address"
      repeated :coins, :message, 2, "cosmos.base.v1beta1.Coin", json_name: "coins"
    end
    add_message "cosmos.bank.v1beta1.Supply" do
      repeated :total, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "total"
    end
    add_message "cosmos.bank.v1beta1.DenomUnit" do
      optional :denom, :string, 1, json_name: "denom"
      optional :exponent, :uint32, 2, json_name: "exponent"
      repeated :aliases, :string, 3, json_name: "aliases"
    end
    add_message "cosmos.bank.v1beta1.Metadata" do
      optional :description, :string, 1, json_name: "description"
      repeated :denom_units, :message, 2, "cosmos.bank.v1beta1.DenomUnit", json_name: "denomUnits"
      optional :base, :string, 3, json_name: "base"
      optional :display, :string, 4, json_name: "display"
      optional :name, :string, 5, json_name: "name"
      optional :symbol, :string, 6, json_name: "symbol"
      optional :uri, :string, 7, json_name: "uri"
      optional :uri_hash, :string, 8, json_name: "uriHash"
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Bank
        module V1beta1
          module Bank
            Params = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.Params").msgclass
            SendEnabled = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.SendEnabled").msgclass
            Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.Input").msgclass
            Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.Output").msgclass
            Supply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.Supply").msgclass
            DenomUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.DenomUnit").msgclass
            Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.Metadata").msgclass
          end
        end
      end
    end
  end
end
