# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/bank/v1beta1/bank.proto

require "google/protobuf"

require "cosmoverse/proto/cosmos_proto/cosmos_pb"
require "cosmoverse/proto/cosmos/base/v1beta1/coin_pb"
require "cosmoverse/proto/cosmos/msg/v1/msg_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/bank/v1beta1/bank.proto", syntax: :proto3) do
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.Params" do
      repeated :send_enabled, :message, 1, "cosmoverse.proto.cosmos.bank.v1beta1.SendEnabled"
      optional :default_send_enabled, :bool, 2
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.SendEnabled" do
      optional :denom, :string, 1
      optional :enabled, :bool, 2
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.Input" do
      optional :address, :string, 1
      repeated :coins, :message, 2, "cosmoverse.proto.cosmos.base.v1beta1.Coin"
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.Output" do
      optional :address, :string, 1
      repeated :coins, :message, 2, "cosmoverse.proto.cosmos.base.v1beta1.Coin"
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.Supply" do
      repeated :total, :message, 1, "cosmoverse.proto.cosmos.base.v1beta1.Coin"
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.DenomUnit" do
      optional :denom, :string, 1
      optional :exponent, :uint32, 2
      repeated :aliases, :string, 3
    end
    add_message "cosmoverse.proto.cosmos.bank.v1beta1.Metadata" do
      optional :description, :string, 1
      repeated :denom_units, :message, 2, "cosmoverse.proto.cosmos.bank.v1beta1.DenomUnit"
      optional :base, :string, 3
      optional :display, :string, 4
      optional :name, :string, 5
      optional :symbol, :string, 6
      optional :uri, :string, 7
      optional :uri_hash, :string, 8
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Bank
        module V1beta1
          Params = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.Params").msgclass
          SendEnabled = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.SendEnabled").msgclass
          Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.Input").msgclass
          Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.Output").msgclass
          Supply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.Supply").msgclass
          DenomUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.DenomUnit").msgclass
          Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmoverse.proto.cosmos.bank.v1beta1.Metadata").msgclass
        end
      end
    end
  end
end
