# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/bank/v1beta1/query.proto

require 'google/protobuf'

require 'cosmoverse/proto/cosmos/base/query/v1beta1/pagination_pb'
require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'google/api/annotations_pb'
require 'cosmoverse/proto/cosmos/base/v1beta1/coin_pb'
require 'cosmoverse/proto/cosmos/bank/v1beta1/bank_pb'
require 'cosmoverse/proto/cosmos_proto/cosmos_pb'
require 'cosmoverse/proto/cosmos/query/v1/query_pb'
require 'cosmoverse/proto/amino/amino_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/bank/v1beta1/query.proto", :syntax => :proto3) do
    add_message "cosmos.bank.v1beta1.QueryBalanceRequest" do
      optional :address, :string, 1, json_name: "address"
      optional :denom, :string, 2, json_name: "denom"
    end
    add_message "cosmos.bank.v1beta1.QueryBalanceResponse" do
      optional :balance, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "balance"
    end
    add_message "cosmos.bank.v1beta1.QueryAllBalancesRequest" do
      optional :address, :string, 1, json_name: "address"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
      optional :resolve_denom, :bool, 3, json_name: "resolveDenom"
    end
    add_message "cosmos.bank.v1beta1.QueryAllBalancesResponse" do
      repeated :balances, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "balances"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySpendableBalancesRequest" do
      optional :address, :string, 1, json_name: "address"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySpendableBalancesResponse" do
      repeated :balances, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "balances"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySpendableBalanceByDenomRequest" do
      optional :address, :string, 1, json_name: "address"
      optional :denom, :string, 2, json_name: "denom"
    end
    add_message "cosmos.bank.v1beta1.QuerySpendableBalanceByDenomResponse" do
      optional :balance, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "balance"
    end
    add_message "cosmos.bank.v1beta1.QueryTotalSupplyRequest" do
      optional :pagination, :message, 1, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QueryTotalSupplyResponse" do
      repeated :supply, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "supply"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySupplyOfRequest" do
      optional :denom, :string, 1, json_name: "denom"
    end
    add_message "cosmos.bank.v1beta1.QuerySupplyOfResponse" do
      optional :amount, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "amount"
    end
    add_message "cosmos.bank.v1beta1.QueryParamsRequest" do
    end
    add_message "cosmos.bank.v1beta1.QueryParamsResponse" do
      optional :params, :message, 1, "cosmos.bank.v1beta1.Params", json_name: "params"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomsMetadataRequest" do
      optional :pagination, :message, 1, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomsMetadataResponse" do
      repeated :metadatas, :message, 1, "cosmos.bank.v1beta1.Metadata", json_name: "metadatas"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomMetadataRequest" do
      optional :denom, :string, 1, json_name: "denom"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomMetadataResponse" do
      optional :metadata, :message, 1, "cosmos.bank.v1beta1.Metadata", json_name: "metadata"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomOwnersRequest" do
      optional :denom, :string, 1, json_name: "denom"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.DenomOwner" do
      optional :address, :string, 1, json_name: "address"
      optional :balance, :message, 2, "cosmos.base.v1beta1.Coin", json_name: "balance"
    end
    add_message "cosmos.bank.v1beta1.QueryDenomOwnersResponse" do
      repeated :denom_owners, :message, 1, "cosmos.bank.v1beta1.DenomOwner", json_name: "denomOwners"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySendEnabledRequest" do
      repeated :denoms, :string, 1, json_name: "denoms"
      optional :pagination, :message, 99, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.bank.v1beta1.QuerySendEnabledResponse" do
      repeated :send_enabled, :message, 1, "cosmos.bank.v1beta1.SendEnabled", json_name: "sendEnabled"
      optional :pagination, :message, 99, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Bank
        module V1beta1
          module Query
            QueryBalanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryBalanceRequest").msgclass
            QueryBalanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryBalanceResponse").msgclass
            QueryAllBalancesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryAllBalancesRequest").msgclass
            QueryAllBalancesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryAllBalancesResponse").msgclass
            QuerySpendableBalancesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySpendableBalancesRequest").msgclass
            QuerySpendableBalancesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySpendableBalancesResponse").msgclass
            QuerySpendableBalanceByDenomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySpendableBalanceByDenomRequest").msgclass
            QuerySpendableBalanceByDenomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySpendableBalanceByDenomResponse").msgclass
            QueryTotalSupplyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryTotalSupplyRequest").msgclass
            QueryTotalSupplyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryTotalSupplyResponse").msgclass
            QuerySupplyOfRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySupplyOfRequest").msgclass
            QuerySupplyOfResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySupplyOfResponse").msgclass
            QueryParamsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryParamsRequest").msgclass
            QueryParamsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryParamsResponse").msgclass
            QueryDenomsMetadataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomsMetadataRequest").msgclass
            QueryDenomsMetadataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomsMetadataResponse").msgclass
            QueryDenomMetadataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomMetadataRequest").msgclass
            QueryDenomMetadataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomMetadataResponse").msgclass
            QueryDenomOwnersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomOwnersRequest").msgclass
            DenomOwner = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.DenomOwner").msgclass
            QueryDenomOwnersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QueryDenomOwnersResponse").msgclass
            QuerySendEnabledRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySendEnabledRequest").msgclass
            QuerySendEnabledResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.bank.v1beta1.QuerySendEnabledResponse").msgclass
          end
        end
      end
    end
  end
end
