# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cosmos/bank/v1beta1/query.proto for package 'Cosmoverse.Proto.Cosmos.Bank.V1beta1.Query'

require 'grpc'
require 'cosmoverse/proto/cosmos/bank/v1beta1/query_pb'

module Cosmoverse
  module Proto
    module Cosmos
      module Bank
        module V1beta1
          module Query
            module Query
              # Query defines the gRPC querier service.
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'cosmos.bank.v1beta1.Query'

                # Balance queries the balance of a single coin for a single account.
                rpc :Balance, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryBalanceRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryBalanceResponse
                # AllBalances queries the balance of all coins for a single account.
                #
                # When called from another module, this query might consume a high amount of
                # gas if the pagination field is incorrectly set.
                rpc :AllBalances, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryAllBalancesRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryAllBalancesResponse
                # SpendableBalances queries the spenable balance of all coins for a single
                # account.
                #
                # When called from another module, this query might consume a high amount of
                # gas if the pagination field is incorrectly set.
                #
                # Since: cosmos-sdk 0.46
                rpc :SpendableBalances, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySpendableBalancesRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySpendableBalancesResponse
                # TotalSupply queries the total supply of all coins.
                #
                # When called from another module, this query might consume a high amount of
                # gas if the pagination field is incorrectly set.
                rpc :TotalSupply, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryTotalSupplyRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryTotalSupplyResponse
                # SupplyOf queries the supply of a single coin.
                #
                # When called from another module, this query might consume a high amount of
                # gas if the pagination field is incorrectly set.
                rpc :SupplyOf, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySupplyOfRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySupplyOfResponse
                # Params queries the parameters of x/bank module.
                rpc :Params, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryParamsRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryParamsResponse
                # DenomsMetadata queries the client metadata of a given coin denomination.
                rpc :DenomMetadata, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomMetadataRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomMetadataResponse
                # DenomsMetadata queries the client metadata for all registered coin
                # denominations.
                rpc :DenomsMetadata, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomsMetadataRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomsMetadataResponse
                # DenomOwners queries for all account addresses that own a particular token
                # denomination.
                #
                # When called from another module, this query might consume a high amount of
                # gas if the pagination field is incorrectly set.
                #
                # Since: cosmos-sdk 0.46
                rpc :DenomOwners, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomOwnersRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QueryDenomOwnersResponse
                # SendEnabled queries for SendEnabled entries.
                #
                # This query only returns denominations that have specific SendEnabled settings.
                # Any denomination that does not have a specific setting will use the default
                # params.default_send_enabled, and will not be returned by this query.
                #
                # Since: cosmos-sdk 0.47
                rpc :SendEnabled, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySendEnabledRequest, ::Cosmoverse::Proto::Cosmos::Bank::V1beta1::Query::QuerySendEnabledResponse
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
