# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cosmos/tx/v1beta1/service.proto for package 'Cosmoverse.Proto.Cosmos.Tx.V1beta1.Service'

require 'grpc'
require 'cosmoverse/proto/cosmos/tx/v1beta1/service_pb'

module Cosmoverse
  module Proto
    module Cosmos
      module Tx
        module V1beta1
          module Service
            module Service
              # Service defines a gRPC service for interacting with transactions.
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'cosmos.tx.v1beta1.Service'

                # Simulate simulates executing a transaction for estimating gas usage.
                rpc :Simulate, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::SimulateRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::SimulateResponse
                # GetTx fetches a tx by hash.
                rpc :GetTx, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetTxRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetTxResponse
                # BroadcastTx broadcast transaction.
                rpc :BroadcastTx, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::BroadcastTxRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::BroadcastTxResponse
                # GetTxsEvent fetches txs by event.
                rpc :GetTxsEvent, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetTxsEventRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetTxsEventResponse
                # GetBlockWithTxs fetches a block with decoded txs.
                #
                # Since: cosmos-sdk 0.45.2
                rpc :GetBlockWithTxs, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetBlockWithTxsRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::GetBlockWithTxsResponse
                # TxDecode decodes the transaction.
                #
                # Since: cosmos-sdk 0.47
                rpc :TxDecode, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxDecodeRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxDecodeResponse
                # TxEncode encodes the transaction.
                #
                # Since: cosmos-sdk 0.47
                rpc :TxEncode, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxEncodeRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxEncodeResponse
                # TxEncodeAmino encodes an Amino transaction from JSON to encoded bytes.
                #
                # Since: cosmos-sdk 0.47
                rpc :TxEncodeAmino, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxEncodeAminoRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxEncodeAminoResponse
                # TxDecodeAmino decodes an Amino transaction from encoded bytes to JSON.
                #
                # Since: cosmos-sdk 0.47
                rpc :TxDecodeAmino, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxDecodeAminoRequest, ::Cosmoverse::Proto::Cosmos::Tx::V1beta1::Service::TxDecodeAminoResponse
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
