# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/tx/v1beta1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'cosmoverse/proto/cosmos/base/abci/v1beta1/abci_pb'
require 'cosmoverse/proto/cosmos/tx/v1beta1/tx_pb'
require 'cosmoverse/proto/cosmos/base/query/v1beta1/pagination_pb'
require 'cosmoverse/proto/tendermint/types/block_pb'
require 'cosmoverse/proto/tendermint/types/types_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/tx/v1beta1/service.proto", :syntax => :proto3) do
    add_message "cosmos.tx.v1beta1.GetTxsEventRequest" do
      repeated :events, :string, 1, json_name: "events"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
      optional :order_by, :enum, 3, "cosmos.tx.v1beta1.OrderBy", json_name: "orderBy"
      optional :page, :uint64, 4, json_name: "page"
      optional :limit, :uint64, 5, json_name: "limit"
    end
    add_message "cosmos.tx.v1beta1.GetTxsEventResponse" do
      repeated :txs, :message, 1, "cosmos.tx.v1beta1.Tx", json_name: "txs"
      repeated :tx_responses, :message, 2, "cosmos.base.abci.v1beta1.TxResponse", json_name: "txResponses"
      optional :pagination, :message, 3, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
      optional :total, :uint64, 4, json_name: "total"
    end
    add_message "cosmos.tx.v1beta1.BroadcastTxRequest" do
      optional :tx_bytes, :bytes, 1, json_name: "txBytes"
      optional :mode, :enum, 2, "cosmos.tx.v1beta1.BroadcastMode", json_name: "mode"
    end
    add_message "cosmos.tx.v1beta1.BroadcastTxResponse" do
      optional :tx_response, :message, 1, "cosmos.base.abci.v1beta1.TxResponse", json_name: "txResponse"
    end
    add_message "cosmos.tx.v1beta1.SimulateRequest" do
      optional :tx, :message, 1, "cosmos.tx.v1beta1.Tx", json_name: "tx"
      optional :tx_bytes, :bytes, 2, json_name: "txBytes"
    end
    add_message "cosmos.tx.v1beta1.SimulateResponse" do
      optional :gas_info, :message, 1, "cosmos.base.abci.v1beta1.GasInfo", json_name: "gasInfo"
      optional :result, :message, 2, "cosmos.base.abci.v1beta1.Result", json_name: "result"
    end
    add_message "cosmos.tx.v1beta1.GetTxRequest" do
      optional :hash, :string, 1, json_name: "hash"
    end
    add_message "cosmos.tx.v1beta1.GetTxResponse" do
      optional :tx, :message, 1, "cosmos.tx.v1beta1.Tx", json_name: "tx"
      optional :tx_response, :message, 2, "cosmos.base.abci.v1beta1.TxResponse", json_name: "txResponse"
    end
    add_message "cosmos.tx.v1beta1.GetBlockWithTxsRequest" do
      optional :height, :int64, 1, json_name: "height"
      optional :pagination, :message, 2, "cosmos.base.query.v1beta1.PageRequest", json_name: "pagination"
    end
    add_message "cosmos.tx.v1beta1.GetBlockWithTxsResponse" do
      repeated :txs, :message, 1, "cosmos.tx.v1beta1.Tx", json_name: "txs"
      optional :block_id, :message, 2, "tendermint.types.BlockID", json_name: "blockId"
      optional :block, :message, 3, "tendermint.types.Block", json_name: "block"
      optional :pagination, :message, 4, "cosmos.base.query.v1beta1.PageResponse", json_name: "pagination"
    end
    add_enum "cosmos.tx.v1beta1.OrderBy" do
      value :ORDER_BY_UNSPECIFIED, 0
      value :ORDER_BY_ASC, 1
      value :ORDER_BY_DESC, 2
    end
    add_enum "cosmos.tx.v1beta1.BroadcastMode" do
      value :BROADCAST_MODE_UNSPECIFIED, 0
      value :BROADCAST_MODE_BLOCK, 1
      value :BROADCAST_MODE_SYNC, 2
      value :BROADCAST_MODE_ASYNC, 3
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Tx
        module V1beta1
          module Service
            GetTxsEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetTxsEventRequest").msgclass
            GetTxsEventResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetTxsEventResponse").msgclass
            BroadcastTxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.BroadcastTxRequest").msgclass
            BroadcastTxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.BroadcastTxResponse").msgclass
            SimulateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.SimulateRequest").msgclass
            SimulateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.SimulateResponse").msgclass
            GetTxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetTxRequest").msgclass
            GetTxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetTxResponse").msgclass
            GetBlockWithTxsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetBlockWithTxsRequest").msgclass
            GetBlockWithTxsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.GetBlockWithTxsResponse").msgclass
            OrderBy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.OrderBy").enummodule
            BroadcastMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.BroadcastMode").enummodule
          end
        end
      end
    end
  end
end
