# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/tx/v1beta1/tx.proto

require 'google/protobuf'

require 'cosmoverse/proto/gogoproto/gogo_pb'
require 'cosmoverse/proto/cosmos/crypto/multisig/v1beta1/multisig_pb'
require 'cosmoverse/proto/cosmos/base/v1beta1/coin_pb'
require 'cosmoverse/proto/cosmos/tx/signing/v1beta1/signing_pb'
require 'google/protobuf/any_pb'
require 'cosmoverse/proto/cosmos_proto/cosmos_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cosmos/tx/v1beta1/tx.proto", :syntax => :proto3) do
    add_message "cosmos.tx.v1beta1.Tx" do
      optional :body, :message, 1, "cosmos.tx.v1beta1.TxBody", json_name: "body"
      optional :auth_info, :message, 2, "cosmos.tx.v1beta1.AuthInfo", json_name: "authInfo"
      repeated :signatures, :bytes, 3, json_name: "signatures"
    end
    add_message "cosmos.tx.v1beta1.TxRaw" do
      optional :body_bytes, :bytes, 1, json_name: "bodyBytes"
      optional :auth_info_bytes, :bytes, 2, json_name: "authInfoBytes"
      repeated :signatures, :bytes, 3, json_name: "signatures"
    end
    add_message "cosmos.tx.v1beta1.SignDoc" do
      optional :body_bytes, :bytes, 1, json_name: "bodyBytes"
      optional :auth_info_bytes, :bytes, 2, json_name: "authInfoBytes"
      optional :chain_id, :string, 3, json_name: "chainId"
      optional :account_number, :uint64, 4, json_name: "accountNumber"
    end
    add_message "cosmos.tx.v1beta1.SignDocDirectAux" do
      optional :body_bytes, :bytes, 1, json_name: "bodyBytes"
      optional :public_key, :message, 2, "google.protobuf.Any", json_name: "publicKey"
      optional :chain_id, :string, 3, json_name: "chainId"
      optional :account_number, :uint64, 4, json_name: "accountNumber"
      optional :sequence, :uint64, 5, json_name: "sequence"
      optional :tip, :message, 6, "cosmos.tx.v1beta1.Tip", json_name: "tip"
    end
    add_message "cosmos.tx.v1beta1.TxBody" do
      repeated :messages, :message, 1, "google.protobuf.Any", json_name: "messages"
      optional :memo, :string, 2, json_name: "memo"
      optional :timeout_height, :uint64, 3, json_name: "timeoutHeight"
      repeated :extension_options, :message, 1023, "google.protobuf.Any", json_name: "extensionOptions"
      repeated :non_critical_extension_options, :message, 2047, "google.protobuf.Any", json_name: "nonCriticalExtensionOptions"
    end
    add_message "cosmos.tx.v1beta1.AuthInfo" do
      repeated :signer_infos, :message, 1, "cosmos.tx.v1beta1.SignerInfo", json_name: "signerInfos"
      optional :fee, :message, 2, "cosmos.tx.v1beta1.Fee", json_name: "fee"
      optional :tip, :message, 3, "cosmos.tx.v1beta1.Tip", json_name: "tip"
    end
    add_message "cosmos.tx.v1beta1.SignerInfo" do
      optional :public_key, :message, 1, "google.protobuf.Any", json_name: "publicKey"
      optional :mode_info, :message, 2, "cosmos.tx.v1beta1.ModeInfo", json_name: "modeInfo"
      optional :sequence, :uint64, 3, json_name: "sequence"
    end
    add_message "cosmos.tx.v1beta1.ModeInfo" do
      oneof :sum do
        optional :single, :message, 1, "cosmos.tx.v1beta1.ModeInfo.Single", json_name: "single"
        optional :multi, :message, 2, "cosmos.tx.v1beta1.ModeInfo.Multi", json_name: "multi"
      end
    end
    add_message "cosmos.tx.v1beta1.ModeInfo.Single" do
      optional :mode, :enum, 1, "cosmos.tx.signing.v1beta1.SignMode", json_name: "mode"
    end
    add_message "cosmos.tx.v1beta1.ModeInfo.Multi" do
      optional :bitarray, :message, 1, "cosmos.crypto.multisig.v1beta1.CompactBitArray", json_name: "bitarray"
      repeated :mode_infos, :message, 2, "cosmos.tx.v1beta1.ModeInfo", json_name: "modeInfos"
    end
    add_message "cosmos.tx.v1beta1.Fee" do
      repeated :amount, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "amount"
      optional :gas_limit, :uint64, 2, json_name: "gasLimit"
      optional :payer, :string, 3, json_name: "payer"
      optional :granter, :string, 4, json_name: "granter"
    end
    add_message "cosmos.tx.v1beta1.Tip" do
      repeated :amount, :message, 1, "cosmos.base.v1beta1.Coin", json_name: "amount"
      optional :tipper, :string, 2, json_name: "tipper"
    end
    add_message "cosmos.tx.v1beta1.AuxSignerData" do
      optional :address, :string, 1, json_name: "address"
      optional :sign_doc, :message, 2, "cosmos.tx.v1beta1.SignDocDirectAux", json_name: "signDoc"
      optional :mode, :enum, 3, "cosmos.tx.signing.v1beta1.SignMode", json_name: "mode"
      optional :sig, :bytes, 4, json_name: "sig"
    end
  end
end

module Cosmoverse
  module Proto
    module Cosmos
      module Tx
        module V1beta1
          module Tx
            Tx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.Tx").msgclass
            TxRaw = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.TxRaw").msgclass
            SignDoc = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.SignDoc").msgclass
            SignDocDirectAux = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.SignDocDirectAux").msgclass
            TxBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.TxBody").msgclass
            AuthInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.AuthInfo").msgclass
            SignerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.SignerInfo").msgclass
            ModeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.ModeInfo").msgclass
            ModeInfo::Single = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.ModeInfo.Single").msgclass
            ModeInfo::Multi = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.ModeInfo.Multi").msgclass
            Fee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.Fee").msgclass
            Tip = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.Tip").msgclass
            AuxSignerData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.tx.v1beta1.AuxSignerData").msgclass
          end
        end
      end
    end
  end
end
