# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gogoproto/gogo.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gogoproto/gogo.proto", :syntax => :proto2) do
  end
end

module Cosmoverse
  module Proto
    module Gogoproto
    end
  end
end
