name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Start Cosmos test node
      run: docker-compose up --detach --build
    - name: Wait for Cosmos
      run: sleep 10
    - name: Run the default task
      run: bundle exec rake
